### ISSUE TITLE
Where is the image or images

### ISSUE THREAD

**Issue by danzen** [t3dotgg/1app5stacks#21]
I poked around for 5 minutes... and could not find the images or is it a sprite sheet with images.  Is it not in this repository?  I checked some of the code and found some hints.... but here is a hint, if we can't find the images... the project is way too complex.  Maybe I just got unlucky.  It was certainly disappointing finding an images folder... nope... not in there, etc. If someone could point me in the right direction... thanks.

**Comment by Marcial1234** [comment]
What I was able to find was that the images are downloaded as needed from the Pokemon API: https://github.com/t3dotgg/1app5stacks/blob/main/go-graphql-spa-version/react-gql-spa/src/utils/sprite.tsx#L10

Which are actually stored here: https://github.com/PokeAPI/sprites

**Comment by danzen** [comment]
Thanks!  Too bad they are not on Sprite Sheets - but maybe will do that - we will see.  Cheers.
